Реализация логики tree. для примера работы добавлены каталоги и html-…
lJarSl/mitsuk-margarita-otus pull request #3
Opened 2018-08-15 11:28 UTC by lJarSl

…файлы

2018-09-02 11:10 UTC, korzio commented
На таком вызове у меня ошибка:

```
npm run tree ./

node tree.js "./"

TypeError: Cannot read property 'readdir' of undefined
```

2018-09-02 11:33 UTC, korzio requested changes
Проверил код в Вашем репозитории - для папок `node`, `javascript` работает, а вот для всего репозитория - нет. Добавил вывод количества промисов

```
promisesCount 9
tree.js:66
promisesCount 8
tree.js:66
promisesCount 7
tree.js:66
promisesCount 7
tree.js:66
promisesCount 8
tree.js:66
promisesCount 10
tree.js:66
promisesCount 9
tree.js:66
promisesCount 8
tree.js:66
promisesCount 8
tree.js:66
promisesCount 9
tree.js:66
promisesCount 8
tree.js:66
promisesCount 7
tree.js:66
promisesCount 7
tree.js:66
promisesCount 8
tree.js:66
promisesCount 7
tree.js:66
promisesCount 7
tree.js:66
promisesCount 6
tree.js:66
promisesCount 7
tree.js:66
promisesCount 6
tree.js:66
promisesCount 5
tree.js:66
promisesCount 4
tree.js:66
promisesCount 4
tree.js:66
promisesCount 3
tree.js:66
```

Есть идеи почему так получается?

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +        this.promisesCount = 1
Вы знаете, какой здесь контекст `this`?

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +const fs = require('fs')
Здесь можно улучшить читаемость кода, используя `destructuring` - экспортируя все используемые функции. Что-то в роде

```
const { promises: { readdir, stat } } = require('fs')
```

Тогда можно обойтись без введения новых функций на [:9](https://github.com/lJarSl/mitsuk-margarita-otus/pull/3/files#diff-10a0630db38ec95c87aa71731e54364fR9) и [:12](https://github.com/lJarSl/mitsuk-margarita-otus/pull/3/files#diff-10a0630db38ec95c87aa71731e54364fR12)

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +        throw 'ожидается string, передано ' + typeof stringDir
Помните, мы говорили, что лучше выбрасывать в исключение `error`, нежели строку?

2018-09-02 11:33 UTC, korzio commented on README.md
> +### Для проверки:
Супер, очень удобно!

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +    async function getPromiceReaddir(dir) {
С другой стороны, раз уж Вы создаете `async` функции, логично было бы попробовать `await`

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +                const newPath = `${path}/${pathsContent[key]}`
Для конкатенации путей лучше всего использовать метод `join()` модуля [`path`](https://nodejs.org/api/path.html), иначе на выходе получаются результаты вроде

```
 [ './/folder', './/folder/12', './/folder/1', './/folder/1/2' ],
```

2018-09-02 11:33 UTC, korzio commented on node/tree-lesson-4/tree.js
> +                            promisesCount++
А здесь `promisesCount` без `this`, почему так?

2018-09-08 10:56 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +        this.promisesCount = 1
тут глобал

2018-09-08 10:57 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +        this.promisesCount = 1
изменила на объявление с let

2018-09-08 11:00 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +                            promisesCount++
потому что мы их получаем из замыкания

2018-09-08 11:00 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +        throw 'ожидается string, передано ' + typeof stringDir
поправила

2018-09-08 11:01 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +    async function getPromiceReaddir(dir) {
подумала обойтись без async )))

2018-09-08 11:05 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +const fs = require('fs')
Вау!) это очень круто))) спасибо БОЛЬШОЕ!)))

2018-09-08 11:06 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +                const newPath = `${path}/${pathsContent[key]}`
с использованием join модуля path теперь все сепараторы двойные =(

2018-09-08 11:06 UTC, lJarSl commented on node/tree-lesson-4/tree.js
> +                const newPath = `${path}/${pathsContent[key]}`
это нормально?

2018-09-09 18:49 UTC, korzio approved these changes

2018-09-09 18:49 UTC, korzio commented on node/tree-lesson-4/tree.js
> +                const newPath = `${path}/${pathsContent[key]}`
Странно, конечно, но по крайней мере, должно работать на разных операционных системах

2018-09-09 18:49 UTC, korzio commented on node/tree-lesson-4/tree.js
> +const path = require('path');
и `join` тоже можно деструктурировать, но это я так, разницы нет, и так хорошо

2018-09-09 18:53 UTC, korzio commented
Код хороший, единственное - https://github.com/lJarSl/mitsuk-margarita-otus/pull/3#pullrequestreview-151617091

эта ситуация все равно воспроизводится

2018-09-11 19:12 UTC, luchianenco commented
у меня код не работает ... логика с promisesCount скорее всего не правильно построена
Она работает только когда простая структура в папке указана
когда более сложное дерево то код ведет себя не правильно

2018-12-15 14:41 UTC, merged