Приложение для сохранения и показа RSS
lJarSl/mitsuk-margarita-otus pull request #8
Opened 2018-11-22 14:16 UTC by lJarSl

2018-11-22 20:24 UTC, thoughtspile requested changes

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +app.get('/', function (req, res) {
Лучше не прописывать каждый явно, а использовать `express.static` — https://expressjs.com/en/starter/static-files.html

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +    res.sendfile(__dirname + '/view/index2.html');
со static придется  переложить во `/view/articles/index.html`

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +    .catch( console.log );
Стоит ответить ошибкой,  то у клиета запрос останется висеть

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +app.get('/getallrss', function(req, res) {
Задание называется "проектируем REST API", так что лучше промоделировать ресурсы по ресту:
- `GET /channel` — список
- `POST /channel` — создать
- `GET /channel/:id` — канал

и так далее

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +            res.send({ error: 'Parameters are expected not all' });
и статус еще (для валидации обычно 422)

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +            res.send({ error: 'Parameters are expected not all' });
и тут наверное return, а то функция дальше выполняется

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +    res.contentType('json');
а `.contentType` кажется не нужен

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +app.post('/articles/get', function (req, res) {
опять про рест — непонятно, зачем тут post — мы же не изменяем состояние сервера

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/core/db.js
> +    let line = new Channel(data);
тут та же проблема, что в прошлом задании — нет защиты от дубликатов.

2018-11-22 20:24 UTC, thoughtspile commented on node/nodeJSRestAPI/core/db.js
> +    articles: [articlesSchema]
Не советую схемы с вложенными массивами — сложно писать запросы вида "найди все записи по условию", особенно с индексами. Лучше все таки по старинке сложить в 2 коллекции и джойнить.

2018-11-22 21:34 UTC, lJarSl commented on node/nodeJSRestAPI/core/db.js
> +    let line = new Channel(data);
добавила unique

2018-11-22 21:35 UTC, lJarSl commented on node/nodeJSRestAPI/core/db.js
> +    articles: [articlesSchema]
мне тоже это показалось странным)
до этого не было опыта работы с монго

2018-11-22 21:37 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +            res.send({ error: 'Parameters are expected not all' });
поправила

2018-11-22 21:39 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +    .catch( console.log );
сделала вывод в консоль, ответ со статусом и return

2018-11-22 21:40 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +app.post('/articles/get', function (req, res) {
теперь через get

2018-11-22 21:42 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +    res.contentType('json');
действительно. Это было где-то в best practice примерах кажется. Но и без этого работает

2018-11-22 22:01 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +    res.sendfile(__dirname + '/view/index2.html');
исправила

2018-11-22 22:02 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +app.get('/', function (req, res) {
исправила

2018-11-22 22:09 UTC, lJarSl commented on node/nodeJSRestAPI/main.js
> +app.get('/getallrss', function(req, res) {
REST первой зрелости готов

2018-12-09 13:05 UTC, thoughtspile commented on node/nodeJSRestAPI/main.js
> +    res.contentType('json');
Возможно, года 4 назад это было актуально

2018-12-09 13:12 UTC, thoughtspile requested changes

2018-12-09 13:12 UTC, thoughtspile commented on node/nodeJSRestAPI/core/routes.js
> +    app.post('/channel/save', actions.saveChannel);
Не, тут получается что мы создаем канал с `id == "save"` 
Либо `POST / PUT /channel/:id`, если клиент сам выбирает id
Либо `POST /channels`, если id выбирает сервер (как сейчас)

2018-12-09 13:12 UTC, thoughtspile commented on node/nodeJSRestAPI/core/logger.js
> +const chalk = require('chalk');
обертка для логгера это здорово, можно потом подпихивать разные реализации (нативный console.log довольно медленный). Сейчас этим заниматься не надо)

2018-12-09 13:12 UTC, thoughtspile commented on node/nodeJSRestAPI/core/routes.js
> +            [].forEach.call(articles, el => {
а может `map`?

2018-12-09 13:12 UTC, thoughtspile commented on node/nodeJSRestAPI/core/routes.js
> +            res.status(200).send({data: data});
а статус 200 и так по умолчанию

2018-12-12 17:12 UTC, lJarSl commented on node/nodeJSRestAPI/core/logger.js
> +const chalk = require('chalk');
не поняла, надо убрать?

2018-12-12 17:18 UTC, lJarSl commented on node/nodeJSRestAPI/core/routes.js
> +            res.status(200).send({data: data});
убрала

2018-12-12 17:26 UTC, lJarSl commented on node/nodeJSRestAPI/core/routes.js
> +            [].forEach.call(articles, el => {
заменила

2018-12-12 17:31 UTC, lJarSl commented on node/nodeJSRestAPI/core/routes.js
> +    app.post('/channel/save', actions.saveChannel);
заменила на POST /channels

2018-12-12 17:31 UTC, lJarSl commented on node/nodeJSRestAPI/core/db.js
> +    let line = new Channel(data);
тут ок?

2018-12-15 14:43 UTC, merged

2018-12-18 07:45 UTC, thoughtspile commented on node/nodeJSRestAPI/core/logger.js
> +const chalk = require('chalk');
Нет-нет, все хорошо